name: Build and test

on: [push, pull_request]

jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.23
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Compile dev server                # Ensure it will build.
        run: go build -v                        # Work path does not matter much.
        working-directory: ./scripts/devserver  # Correct path, regardless.

      - name: Compile application and create distribution
        run: go run -v ./scripts/dist -tagname 0.0.0-${{ github.sha }}
