name: Build and test

on: [push, pull_request]

jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Compile dev server
      run: go build -v ./devserver.go

    - name: Compile application and create distribution
      run: go run -v ./dist.go -tagname 0.0.0-${{ github.sha }}

    - name: Deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
